### ISSUE TITLE
Adequate date in filing name

### ISSUE THREAD

**Issue by checkplease78** [john-friedman/datamule-python#11]
It would be really nice if there was a way to parse the date from the file name when download 10-K forms.
Currently, the date in the filename has no general format - sometimes, the year comes first, sometimes the day comes first, and sometimes the month comes first

For example, 
000103500220000007_vloform10-kx12312019.htm
000103500221000051_vlo-20201231.htm
000171126920000012_evrg-12312019x10k.htm

**Comment by john-friedman** [comment]
Hi @checkplease78, so the file name is currently accension number + primary doc filename which is not defined by me. Would you like me to change it to accension number + filing date YYYYMMDD?

Good issue. This feature was requested before, but I couldn't think of a proper way to format it.

**Comment by checkplease78** [comment]
Yes, that's exactly what I was thinking of. I don't really mind implementing that myself. If you lack contributors, I don't mind implementing this myself

Cheers

**Comment by john-friedman** [comment]
Sure, that would be great!

**Comment by checkplease78** [comment]
Something big came up and unfortunately I won't be able to work on this, let alone do programming in general
Sorry

Cheers
