### ISSUE TITLE
errors in parser

### ISSUE THREAD

**Issue by firmai** [john-friedman/datamule-python#19]
I have a really good way for you to track the errors in your 10-k parse, basically here you can see there are some really be anomalies when you count the words year to year. 

[errors_aapl.csv](https://github.com/user-attachments/files/17831999/errors_aapl.csv)

Some are expected differences, like no risk before 06, but for example this management discussion is an anomaly

![image](https://github.com/user-attachments/assets/55646881-e2ab-4f2d-a0ce-3e59004ecc53)

This seem to be related to it picking up **part 1** in the text and cutting it off after that. Here is what you probably want to do as a form of validation, when you for example found the location start of ITEM7A_MARKET_RISK_DISCLOSURES take the words between [ITEM7A_MARKET_RISK_DISCLOSURES, ITEM7_MANAGEMENT_DISCUSSION] and make sure it is similar in size. Also perhaps this could not only solve as a validation mechanism, but also if you have text from end of ITEM6_RESERVED to start of ITEM7A_MARKET_RISK_DISCLOSURES that is larger than ITEM7_MANAGEMENT_DISCUSSION, then perhaps to instead use that text for ITEM7_MANAGEMENT_DISCUSSION. So in short this method could help for validation and for improving the parser. 

**Appendix**
Some screenshot for 2005

<img width="1695" alt="image" src="https://github.com/user-attachments/assets/0cc1a39e-3f9b-4d04-8d51-89e80c808244">

And for 2006

<img width="1693" alt="image" src="https://github.com/user-attachments/assets/97835fae-5b6f-4b99-bae6-6a50861b3ce4">

**Comment by john-friedman** [comment]
Hi @firmai, these problems should be fixed in the generalized parser coming out soon. (It got delayed by logistics - flew to SF for ODF23, interviews w/accelerators, etc)

I'm going to close this thread, and will dm you when the update is out - let's chat soon.

**Comment by firmai** [comment]
Hey @john-friedman how have your scraper progressed on 10-Ks, its probably the most important document in the database, so willing to help you get it perfect.

**Comment by firmai** [comment]
Maybe it is worth reopening if it is still wip
