### ISSUE TITLE
Downloader not fetching any 13F-HR filings.

### ISSUE THREAD

**Issue by crova** [john-friedman/datamule-python#20]
Before anything, thanks for the great work, the library is awesome.

I managed to get some 10K forms but I'm having trouble with 13F-HR ones.

The simple script below runs but don't download anything:
```python
import datamule as dm
downloader = dm.Downloader()
downloader.download(form='13F-HR',cik='895419',file_types=['INFORMATION TABLE'],date=('2024-09-14','2024-09-16'))
```

I know for a fact that there are 13F filings for this cik, am I missing something here?

Thanks again.

**Comment by john-friedman** [comment]
Hi @crova, are you sure there are 13F filings for this date? I don't see any filings for Wolfspeed between 8/26 and 10/15.

![image](https://github.com/user-attachments/assets/e89766c2-75fe-415e-b981-7c55e37f779a)

**Comment by crova** [comment]
Ooof, sorry @john-friedman , I pasted the wrong dates.
Still, the code below using your dates:
`downloader.download(form='13F-HR',cik='895419',file_types=['INFORMATION TABLE'],date=('2024-08-26','2024-10-15'))`

Don't get anything:
```
Fetching URLs: 100%| | 10/10 [00:00<00:00, 16.63it/s]
https://efts.sec.gov/LATEST/search-index?ciks=0000895419&forms=13F-HR&q=-&file_type=INFORMATION+TABLE&startdt=2024-08-26&enddt=2024-10-15
Total filings: 0
Downloading files: 0it [00:00, ?it/s]

Successfully downloaded 0 out of 0 URLs
```

Could you please share the code you ran to get those filings?

**Comment by john-friedman** [comment]
Hey @crova, no worries! I don't think that CIK has 13f filings:
https://www.sec.gov/edgar/search/#/ciks=0000895419&entityName=WOLFSPEED%252C%2520INC.%2520(WOLF)%2520(CIK%25200000895419)

I got that screenshot from checking directly with the SEC. It's submissions total, not filtered submissions https://www.sec.gov/Archives/edgar/data/895419/

Are you sure you have the right CIK?
```
Wolfspeed, Inc. is an American developer and manufacturer of wide-bandgap semiconductors, focused on silicon...
```

**Comment by john-friedman** [comment]
Ohh.. I think I get the confusion! Yes, the way filings are stored in the SEC it is filings by the company. Are you looking for 13F-HR tables that include Wolfspeed?

For that I would use `downloader.download_dataset(dataset='13f_information_table')`
then select all rows which have wolfspeed's cik

**Comment by crova** [comment]
I knew I was doing something dumb.

Thank you very much @john-friedman , that works like a charm.
I'm closing this.
Thanks again for the time and for the great work.

**Comment by john-friedman** [comment]
No problem! Also - you're not being dumb, my documentation needs work. Posts like this help me make them better.
