### ISSUE TITLE
Numerous XML downloads on live filings 

### ISSUE THREAD

**Issue by binary53** [john-friedman/datamule-python#24]
I tried to monitor for the newly filed Form 4 filings and it downloads a bunch of xml files which are not the actual filing. 

Secondly, instead of providing real time filings, I think it gave me everything from 11-26 through 11-28. Below is the code I used.

# Import the library first
import datamule as dm

# Create a downloader instance
downloader = dm.Downloader()

# Use the download method instead of watch
# The exact method name may depend on your version of datamule
https://t.co/IydOLouAFF(form='4')

**Comment by john-friedman** [comment]
Hi @binary53, sorry, there is not enough here for me to go on. Can you share your code + output?

**Comment by john-friedman** [comment]
Oh, I see! What's going on is you are getting the XML version of the form 4. The human version looks like [this](https://www.sec.gov/Archives/edgar/data/70858/000095017024114125/xslF345X05/ownership.xml). The human version (html) is autogenerated by the SEC after the XML version is submitted.

To monitor SEC filings in real time
```
import datamule as dm
downloader = dm.Downloader()
downloader.watch(form='4', silent=False) # you can modify silent
```
Note that this doesn't download anything, just watches for new filings. It has a callback function that can be used to download files, but I'm not happy with the current setup.

I'm planning to rewrite the function this week or next to make it easy to do what you want it to do. Can I ask why you want real time updates?

**Comment by binary53** [comment]
Thank you for providing an update to my erroneous setup. Full disclosure, I have a finance/accounting background, so regrettably, I don't understand programming parlance well.  I did want to clarify something.

1. Can you explain what a "callback function" does? Does this mean that I will get an "alert" of some sort when a new filing becomes available? I want to ensure I understand the way the real-time function works.
2. As an investor (and sometimes trader), I want to leverage the Form 4. The Form 4 is required to be filed by company insiders, such as officers, directors, and owners of more than 10% of a company's equity securities, when they buy or sell shares in the company. So for buy transactions, this might be considered by some to be bullish behavior. Having this information as soon as possible could be valuable to some investors, and this is what I was hoping to do. I do still like your tool because my old SEC downloader file stopped working. Something regarding JSON which I know nothing about.

The Form 4 is a common form, but for the most part, the public hasn't had any mechanism to be made aware when they are filed live. Another form that investors monitor is the Form 13D that must be filed with the U.S. Securities and Exchange Commission (SEC) when a person or group acquires more than 5% of a voting class of a company's equity shares. Schedule 13D must be filed within 10 days of the filer reaching a 5% stake or the Form 13G which is used to report a party's ownership of stock which exceeds 5% of a company's total stock issue.

Previously, I tried to reach out to the SEC regarding their EDGAR Public Dissemination Service (PDS) System, but no one would answer or return my calls or emails. I was interested in their program because they claim to be able to provide transmission by Internet connection of all public filings acquired and accepted by EDGAR as soon as reasonably feasible following receipt of filing data by the PDS.

Here is the link to their  https://www.sec.gov/search-filings/public-dissemination-service-system-contact

**Comment by binary53** [comment]
I just sent you an invite on LinkedIn so we can coordinate. 

Would love to be able to talk this through.

**Comment by john-friedman** [comment]
Great, added you.
