### ISSUE TITLE
Filings dates and "submissions_index.csv"

### ISSUE THREAD

**Issue by keeper90** [john-friedman/datamule-python#25]
Several of your examples such as examples/human_readable.ipynb start with df = pl.read_csv('data/submissions_index.csv'). What is this file and where do I find it? It looks very useful to retrieve filing dates.

In a closed issue from 1 month ago you claim to have fixed the filenames and now filing dates should be in the filenames (https://github.com/john-friedman/datamule-python/pull/12). The changes are still not in the package. I already downloaded 300GB-worth of filings and now I need to fix their names because there are no dates. Any pointers?

**Comment by john-friedman** [comment]
Hi @keeper90, sorry for the confusion with filing dates. For issue 12, @anirudj added dates to be stored in filenames. I later replaced this change with a  `save_metadata` argument to the downloader as users requested more metadata. Here is a link to the [docs](https://john-friedman.github.io/datamule-python/usage/downloader.html#metadata).

```
downloader.download(form='10-K',output_dir='10-K',date=('2010-01-01','2010-01-31'),save_metadata=True)
```
Here's a snippet of the metadata.jsonl file

![image](https://github.com/user-attachments/assets/281906b4-db2b-4da5-b880-4273973523e0)

What filings did you download and using what method? I can fix it for you.

**Comment by keeper90** [comment]
I got 10-Ks. I ended up modifying the code myself. It is working but is fairly slow. Any way to do this fast? Think getting metadata for all 10-Ks

**Comment by john-friedman** [comment]
One option is to modify the params for the efts endpoint https://efts.sec.gov/LATEST/search-index?forms=10-K&startdt=2024-09-13&enddt=2024-12-31. You should be able to do 10r/s which is 1000 file dates / seconds. There are 200,000 10-ks or so, so it should complete in a few minutes.

Btw, how long did it take you to download the 10-Ks originally? Not sure if you used the bulk downloader or not.
