### ISSUE TITLE
Future parsers

### ISSUE THREAD

**Issue by john-friedman** [john-friedman/datamule-python#7]
What parsers should I add next?

Currently considering:
- 10-D

**Comment by john-friedman** [comment]
Update: Yesterday I read through ~200 different SEC filing types (out of the total 1616). I believe I can write 3-4 generalized parsers that will be able to parse almost every form type. I'm aiming to get the update out in the next week.

**Comment by firmai** [comment]
That would be a big gift to researchers! Happy to write about it and share it once you have developed it.
