### ISSUE TITLE
Dataset Builder

### ISSUE THREAD

**Issue by firmai** [john-friedman/datamule-python#8]
Your dataset builder is a great idea. There are multiple distinct datasets that I currently have to scrape using regex keywords. I think one can probably create tiny little templates around it.

Executive Compensation Details:
Comprehensive data on salaries, bonuses, stock options, and other compensation elements for top executives across companies.

You might have to have a separate one for options as it is quite specific.

Employee Benefit Plans: Details on retirement plans, health benefits, and other employee compensation schemes.

Mergers and Acquisitions (M&A) Activities: Information on M&A deals, including deal terms.

There are many others to include here, but thought I will keep it shorter

**Comment by john-friedman** [comment]
Hey @firmai, very useful issue. If you have more ideas, I'm happy to hear them.

Btw - I should be releasing an always up to date parsed SEC archive this month. Once that is up, I'll build the always up to date alternative datasets on top of it.
